#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRG2_21222_P7_2_71
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="P5_71")]
	public partial class LINQ_0320210071DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertmsprodi(msprodi instance);
    partial void Updatemsprodi(msprodi instance);
    partial void Deletemsprodi(msprodi instance);
    #endregion
		
		public LINQ_0320210071DataContext() : 
				base(global::PRG2_21222_P7_2_71.Properties.Settings.Default.P5_71ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LINQ_0320210071DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQ_0320210071DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQ_0320210071DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQ_0320210071DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<msprodi> msprodis
		{
			get
			{
				return this.GetTable<msprodi>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.msprodi")]
	public partial class msprodi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_prodi;
		
		private string _nama_prodi;
		
		private string _singkatan;
		
		private string _ka_prodi;
		
		private string _sek_prodi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_prodiChanging(string value);
    partial void Onid_prodiChanged();
    partial void Onnama_prodiChanging(string value);
    partial void Onnama_prodiChanged();
    partial void OnsingkatanChanging(string value);
    partial void OnsingkatanChanged();
    partial void Onka_prodiChanging(string value);
    partial void Onka_prodiChanged();
    partial void Onsek_prodiChanging(string value);
    partial void Onsek_prodiChanged();
    #endregion
		
		public msprodi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_prodi", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_prodi
		{
			get
			{
				return this._id_prodi;
			}
			set
			{
				if ((this._id_prodi != value))
				{
					this.Onid_prodiChanging(value);
					this.SendPropertyChanging();
					this._id_prodi = value;
					this.SendPropertyChanged("id_prodi");
					this.Onid_prodiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_prodi", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nama_prodi
		{
			get
			{
				return this._nama_prodi;
			}
			set
			{
				if ((this._nama_prodi != value))
				{
					this.Onnama_prodiChanging(value);
					this.SendPropertyChanging();
					this._nama_prodi = value;
					this.SendPropertyChanged("nama_prodi");
					this.Onnama_prodiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_singkatan", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string singkatan
		{
			get
			{
				return this._singkatan;
			}
			set
			{
				if ((this._singkatan != value))
				{
					this.OnsingkatanChanging(value);
					this.SendPropertyChanging();
					this._singkatan = value;
					this.SendPropertyChanged("singkatan");
					this.OnsingkatanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ka_prodi", DbType="VarChar(50)")]
		public string ka_prodi
		{
			get
			{
				return this._ka_prodi;
			}
			set
			{
				if ((this._ka_prodi != value))
				{
					this.Onka_prodiChanging(value);
					this.SendPropertyChanging();
					this._ka_prodi = value;
					this.SendPropertyChanged("ka_prodi");
					this.Onka_prodiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sek_prodi", DbType="VarChar(50)")]
		public string sek_prodi
		{
			get
			{
				return this._sek_prodi;
			}
			set
			{
				if ((this._sek_prodi != value))
				{
					this.Onsek_prodiChanging(value);
					this.SendPropertyChanging();
					this._sek_prodi = value;
					this.SendPropertyChanged("sek_prodi");
					this.Onsek_prodiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
